"""Client & Address: model created

Revision ID: 0c0a8c2b6279
Revises: 
Create Date: 2026-01-20 08:57:03.987404

"""
from typing import Sequence, Union
from datetime import datetime
import random

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c0a8c2b6279'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('address_type', sa.String(length=50), nullable=False),
    sa.Column('street', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    # Seed data: Create 10,000 clients with 2-4 addresses each
    connection = op.get_bind()
    
    # Data for generating realistic clients and addresses
    first_names = ['Juan', 'María', 'Pedro', 'Ana', 'Luis', 'Carmen', 'José', 'Isabel', 'Antonio', 'Rosa',
                   'Francisco', 'Laura', 'Manuel', 'Marta', 'David', 'Elena', 'Carlos', 'Lucía', 'Miguel', 'Sara']
    last_names = ['García', 'Rodríguez', 'Martínez', 'López', 'González', 'Pérez', 'Sánchez', 'Ramírez',
                  'Torres', 'Flores', 'Rivera', 'Gómez', 'Díaz', 'Cruz', 'Morales', 'Reyes', 'Gutiérrez']
    
    cities = ['Madrid', 'Barcelona', 'Valencia', 'Sevilla', 'Zaragoza', 'Málaga', 'Murcia', 'Palma',
              'Las Palmas', 'Bilbao', 'Alicante', 'Córdoba', 'Valladolid', 'Vigo', 'Gijón']
    states = ['Comunidad de Madrid', 'Cataluña', 'Comunidad Valenciana', 'Andalucía', 'Aragón',
              'País Vasco', 'Galicia', 'Castilla y León', 'Islas Baleares', 'Canarias']
    
    street_names = ['Calle Mayor', 'Avenida Principal', 'Calle del Sol', 'Plaza España', 'Paseo Marítimo',
                    'Calle Real', 'Avenida Libertad', 'Calle Nueva', 'Plaza Central', 'Calle Flores']
    
    countries = ['España', 'México', 'Argentina', 'Colombia', 'Chile', 'Perú']
    address_types = ['home', 'billing', 'shipping', 'office']
    
    # Insert clients in batches of 1000
    batch_size = 1000
    total_clients = 10000
    
    for batch in range(0, total_clients, batch_size):
        clients_data = []
        addresses_data = []
        
        for i in range(batch, min(batch + batch_size, total_clients)):
            client_id = i + 1
            first_name = random.choice(first_names)
            last_name = random.choice(last_names)
            name = f"{first_name} {last_name}"
            email = f"{first_name.lower()}.{last_name.lower()}.{client_id}@example.com"
            phone = f"+34 {random.randint(600, 799)} {random.randint(100, 999)} {random.randint(100, 999)}"
            
            clients_data.append({
                'id': client_id,
                'name': name,
                'email': email,
                'phone': phone,
                'created_at': datetime.utcnow()
            })
            
            # Create 2-4 addresses per client
            num_addresses = random.randint(2, 4)
            for addr_idx in range(num_addresses):
                street_num = random.randint(1, 999)
                street = f"{random.choice(street_names)} {street_num}"
                city = random.choice(cities)
                state = random.choice(states)
                postal_code = f"{random.randint(10000, 52999)}"
                country = random.choice(countries)
                addr_type = address_types[addr_idx] if addr_idx < len(address_types) else 'other'
                is_default = (addr_idx == 0)  # First address is default
                
                addresses_data.append({
                    'client_id': client_id,
                    'address_type': addr_type,
                    'street': street,
                    'city': city,
                    'state': state,
                    'postal_code': postal_code,
                    'country': country,
                    'is_default': is_default,
                    'created_at': datetime.utcnow()
                })
        
        # Bulk insert for performance
        if clients_data:
            connection.execute(
                sa.text("""
                    INSERT INTO clients (id, name, email, phone, created_at)
                    VALUES (:id, :name, :email, :phone, :created_at)
                """),
                clients_data
            )
        
        if addresses_data:
            connection.execute(
                sa.text("""
                    INSERT INTO addresses (client_id, address_type, street, city, state, postal_code, country, is_default, created_at)
                    VALUES (:client_id, :address_type, :street, :city, :state, :postal_code, :country, :is_default, :created_at)
                """),
                addresses_data
            )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('addresses')
    op.drop_table('clients')
    # ### end Alembic commands ###
